
#include <iostream> 
#include <Windows.h>
using namespace std;
int main()
{
    while (true)
    {
        cout << "          __          \n";
        cout << "       *      *        \n";
        cout << "     *          *        \n";
        cout << "   |              |        \n";
        cout << "   |              |        \n";
        cout << "     *          *        \n";
        cout << "       * ____ *        \n";
        Sleep(300);
        system("cls");
        cout << "          __          \n";
        cout << "        *    *        \n";
        cout << "      *        *        \n";
        cout << "    |            |        \n";
        cout << "    |            |        \n";
        cout << "      *        *        \n";
        cout << "        * ___*        \n";
        Sleep(300);
        system("cls");
        cout << "          __          \n";
        cout << "         *  *        \n";
        cout << "       *      *        \n";
        cout << "     |          |        \n";
        cout << "     |          |        \n";
        cout << "       *      *        \n";
        cout << "         *__*        \n";
        Sleep(300);
        system("cls");
        cout << "          __          \n";
        cout << "          **        \n";
        cout << "        *    *        \n";
        cout << "      |        |        \n";
        cout << "      |        |        \n";
        cout << "        *    *        \n";
        cout << "          **        \n";
        Sleep(300);
        system("cls");
        cout << "          __          \n";
        cout << "          **        \n";
        cout << "         *  *        \n";
        cout << "       |      |        \n";
        cout << "       |      |        \n";
        cout << "         *  *        \n";
        cout << "          **        \n";
        Sleep(300);
        system("cls");

        cout << "          __          \n";
        cout << "          **        \n";
        cout << "          **        \n";
        cout << "        |    |        \n";
        cout << "        |    |        \n";
        cout << "          **        \n";
        cout << "          **        \n";
        Sleep(300);
        system("cls");
        cout << "          __          \n";
        cout << "          **        \n";
        cout << "          **        \n";
        cout << "         |  |        \n";
        cout << "         |  |        \n";
        cout << "          **        \n";
        cout << "          **        \n";
        Sleep(300);
        system("cls");
        cout << "          __          \n";
        cout << "          **        \n";
        cout << "          **        \n";
        cout << "          ||        \n";
        cout << "          ||        \n";
        cout << "          **        \n";
        cout << "          **        \n";
        Sleep(300);
        system("cls");
        cout << "          __          \n";
        cout << "          **        \n";
        cout << "          **        \n";
        cout << "         |  |        \n";
        cout << "         |  |        \n";
        cout << "          **        \n";
        cout << "          **        \n";
        Sleep(300);
        system("cls");

        cout << "          __          \n";
        cout << "          **        \n";
        cout << "          **        \n";
        cout << "        |    |        \n";
        cout << "        |    |        \n";
        cout << "          **        \n";
        cout << "          **        \n";
        Sleep(300);
        system("cls");
        cout << "          __          \n";
        cout << "          **        \n";
        cout << "         *  *        \n";
        cout << "       |      |        \n";
        cout << "       |      |        \n";
        cout << "         *  *        \n";
        cout << "          **        \n";
        Sleep(300);
        system("cls");
        cout << "          __          \n";
        cout << "          **        \n";
        cout << "        *    *        \n";
        cout << "      |        |        \n";
        cout << "      |        |        \n";
        cout << "        *    *        \n";
        cout << "          **        \n";
        Sleep(300);
        system("cls");
        cout << "          __          \n";
        cout << "         *  *        \n";
        cout << "       *      *        \n";
        cout << "     |          |        \n";
        cout << "     |          |        \n";
        cout << "       *      *        \n";
        cout << "         *__*        \n";
        Sleep(300);
        system("cls");
        cout << "          __          \n";
        cout << "        *    *        \n";
        cout << "      *        *        \n";
        cout << "    |            |        \n";
        cout << "    |            |        \n";
        cout << "      *        *        \n";
        cout << "        * ___*        \n";
        Sleep(300);
        system("cls");
    }
}